---
platform: linux

jobs:
- name: deploy-discourse
  plan:
  - get: pipeline-code
    trigger: true
  - put: discourse
    params:
      chart: bitnami/discourse
      version: {{discourse_version}}
      values:
      - pipeline-code/discourse_/overrides/prod/discourse.yaml
      # - pipeline-code/discourse_/overrides/prod/env.yaml

resources:
- name: discourse
  type: helm
  source:
    release: discourse
    cluster_ca: {{cluster_ca}}
    cluster_url: {{cluster_url}}
    token: {{token}}
    namespace: clinic
    repos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami

- name: pipeline-code
  type: git
  source:
    uri: git@github.com:Shreyasks1729/test-tag.git
    branch: main
    private_key: {{git_private_key}}
    tag_filter: "*1.0.0*"
      
resource_types:
- name: helm
  type: docker-image
  source:
    repository: typositoire/concourse-helm3-resource
    tag: v1.13.2
